######################## default configuration ####################
baseURL = "https://paulscheltema.nl/"
languageCode = "nl-nl"
title = "Tiny House Groningen"
theme = "restaurant-hugo"
summaryLength = "10"
paginate = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Tiny Home"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Over ons"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Prijs"
URL = "price"
weight = 4

[[menu.main]]
name = "Nieuws"
URL = "subscribe"
weight = 5

[[menu.main]]
name = "Contact"
URL = "contact-us"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "Paul Scheltema"
description = "Een Tiny House bouwer in Groningen"
# google analitycs ID
google_analitycs_id = "UA-110533565-1"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Copyright &copy; 2021"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
blogTitle = "LATEST <span>BLOG POSTS</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"

############################ footer contact item
[[params.footer.contactItem]]
title = "Telephone"
icon = "fa fa-phone"
content = "06 38155470"

[[params.footer.contactItem]]
title = "Address"
icon = "fa fa-map-marker"
content = "Verlaatweg 7 9791DR Ten Boer"

[[params.footer.contactItem]]
title = "E mail"
icon = "fa fa-envelope"
content = "paulscheltema@gmail.com"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-4.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "dribbble"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/themefisher"
